# Generated by Django 4.2.2 on 2023-06-19 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 19, 19, 22, 3, 498832), editable=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 19, 19, 22, 3, 498832)),
        ),
    ]
